// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innova4b;

import com.innova4b.Pasajero;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Pasajero_Roo_Configurable {
    
    declare @type: Pasajero: @Configurable;
    
}
