// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innova4b;

import com.innova4b.RutaPK;
import java.io.Serializable;

privileged aspect RutaPK_Roo_Serializable {
    
    declare parents: RutaPK implements Serializable;
    
    private static final long RutaPK.serialVersionUID = 1L;
    
}
