// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innova4b;

import com.innova4b.Embarque;
import com.innova4b.EmbarqueDataOnDemand;
import com.innova4b.EmbarqueIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EmbarqueIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EmbarqueIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EmbarqueIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EmbarqueIntegrationTest: @Transactional;
    
    @Autowired
    EmbarqueDataOnDemand EmbarqueIntegrationTest.dod;
    
    @Test
    public void EmbarqueIntegrationTest.testCountEmbarques() {
        Assert.assertNotNull("Data on demand for 'Embarque' failed to initialize correctly", dod.getRandomEmbarque());
        long count = Embarque.countEmbarques();
        Assert.assertTrue("Counter for 'Embarque' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EmbarqueIntegrationTest.testFindEmbarque() {
        Embarque obj = dod.getRandomEmbarque();
        Assert.assertNotNull("Data on demand for 'Embarque' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Embarque' failed to provide an identifier", id);
        obj = Embarque.findEmbarque(id);
        Assert.assertNotNull("Find method for 'Embarque' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Embarque' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EmbarqueIntegrationTest.testFindAllEmbarques() {
        Assert.assertNotNull("Data on demand for 'Embarque' failed to initialize correctly", dod.getRandomEmbarque());
        long count = Embarque.countEmbarques();
        Assert.assertTrue("Too expensive to perform a find all test for 'Embarque', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Embarque> result = Embarque.findAllEmbarques();
        Assert.assertNotNull("Find all method for 'Embarque' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Embarque' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EmbarqueIntegrationTest.testFindEmbarqueEntries() {
        Assert.assertNotNull("Data on demand for 'Embarque' failed to initialize correctly", dod.getRandomEmbarque());
        long count = Embarque.countEmbarques();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Embarque> result = Embarque.findEmbarqueEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Embarque' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Embarque' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EmbarqueIntegrationTest.testFlush() {
        Embarque obj = dod.getRandomEmbarque();
        Assert.assertNotNull("Data on demand for 'Embarque' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Embarque' failed to provide an identifier", id);
        obj = Embarque.findEmbarque(id);
        Assert.assertNotNull("Find method for 'Embarque' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEmbarque(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Embarque' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmbarqueIntegrationTest.testMergeUpdate() {
        Embarque obj = dod.getRandomEmbarque();
        Assert.assertNotNull("Data on demand for 'Embarque' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Embarque' failed to provide an identifier", id);
        obj = Embarque.findEmbarque(id);
        boolean modified =  dod.modifyEmbarque(obj);
        Integer currentVersion = obj.getVersion();
        Embarque merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Embarque' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmbarqueIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Embarque' failed to initialize correctly", dod.getRandomEmbarque());
        Embarque obj = dod.getNewTransientEmbarque(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Embarque' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Embarque' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Embarque' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EmbarqueIntegrationTest.testRemove() {
        Embarque obj = dod.getRandomEmbarque();
        Assert.assertNotNull("Data on demand for 'Embarque' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Embarque' failed to provide an identifier", id);
        obj = Embarque.findEmbarque(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Embarque' with identifier '" + id + "'", Embarque.findEmbarque(id));
    }
    
}
