// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innova4b;

import com.innova4b.Embarque;
import com.innova4b.EmbarqueDataOnDemand;
import com.innova4b.model.AeropuertoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect EmbarqueDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EmbarqueDataOnDemand: @Component;
    
    private Random EmbarqueDataOnDemand.rnd = new SecureRandom();
    
    private List<Embarque> EmbarqueDataOnDemand.data;
    
    @Autowired
    AeropuertoDataOnDemand EmbarqueDataOnDemand.aeropuertoDataOnDemand;
    
    public Embarque EmbarqueDataOnDemand.getNewTransientEmbarque(int index) {
        Embarque obj = new Embarque();
        setIdEmbarque(obj, index);
        setNumero(obj, index);
        return obj;
    }
    
    public void EmbarqueDataOnDemand.setIdEmbarque(Embarque obj, int index) {
        Long idEmbarque = new Integer(index).longValue();
        obj.setIdEmbarque(idEmbarque);
    }
    
    public void EmbarqueDataOnDemand.setNumero(Embarque obj, int index) {
        int numero = index;
        obj.setNumero(numero);
    }
    
    public Embarque EmbarqueDataOnDemand.getSpecificEmbarque(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Embarque obj = data.get(index);
        Long id = obj.getId();
        return Embarque.findEmbarque(id);
    }
    
    public Embarque EmbarqueDataOnDemand.getRandomEmbarque() {
        init();
        Embarque obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Embarque.findEmbarque(id);
    }
    
    public boolean EmbarqueDataOnDemand.modifyEmbarque(Embarque obj) {
        return false;
    }
    
    public void EmbarqueDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Embarque.findEmbarqueEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Embarque' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Embarque>();
        for (int i = 0; i < 10; i++) {
            Embarque obj = getNewTransientEmbarque(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
