/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.21
 * Generated at: 2015-04-17 03:28:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.avion;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import java.util.List;
import java.sql.*;
import com.innova4b.*;
import javax.servlet.http.*;
import javax.servlet.*;

public final class formAvion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/home/noa/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/gestionaena/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153377882000L));
    _jspx_dependants.put("jar:file:/home/noa/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/gestionaena/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153377882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1428696932000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("com.innova4b");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Actividad 1</title>\n");
      out.write("<!-- Bootstrap core JS -->\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\" media=\"screen\">\n");
      out.write("<link\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap-datetimepicker.min.css\"\n");
      out.write("\trel=\"stylesheet\" media=\"screen\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"collapse navbar-collapse navbar-ex1-collapse\">\n");
      out.write("\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Atr&aacute;s</a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("\t<form class=\"form-horizontal\" role=\"form\"\n");
      out.write("\t\taction=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/avion/insercion_mapear\"\n");
      out.write("\t\tmethod=\"post\">\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<label for=\"modelo\" class=\"col-sm-2 control-label\">Modelo</label>\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t<input name=\"modelo\" type=\"text\" class=\"form-control\" id=\"modelo\"\n");
      out.write("\t\t\t\t\tplaceholder=\"Modelo\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<label for=\"max_pasajeros\" class=\"col-sm-2 control-label\">M&aacute;ximo\n");
      out.write("\t\t\t\tPasajeros</label>\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t<input name=\"max_pasajeros\" type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\tid=\"max_pasajeros\" placeholder=\"Máximo número pasajeros\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<label for=\"hora_salida\" class=\"col-sm-2 control-label\">Hora\n");
      out.write("\t\t\t\tSalida</label>\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t<input name=\"hora_salida\" type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\tid=\"hora_salida\" placeholder=\"Hora de Salida: ej(02/03/2015 08:45)\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<label for=\"hora_llegada\" class=\"col-sm-2 control-label\">Hora\n");
      out.write("\t\t\t\tLlegada</label>\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t<input name=\"hora_llegada\" type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\tid=\"hora_llegada\"\n");
      out.write("\t\t\t\t\tplaceholder=\"Hora de Llegada: ej(02/03/2015 08:45)\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<label for=\"codgo_licencia\" class=\"col-sm-2 control-label\">C&oacute;digo\n");
      out.write("\t\t\t\tLicencia</label>\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t<input name=\"codgo_licencia\" type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\tid=\"codgo_licencia\" placeholder=\"Código licencia\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<label for=\"estado_licencia\" class=\"col-sm-2 control-label\">Estado\n");
      out.write("\t\t\t\tLicencia</label>\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t<select id=\"estado_licencia\" name=\"estado_licencia\"\n");
      out.write("\t\t\t\t\tclass=\"form-control\">\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">Activo</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">Caducado</option>\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<label for=\"compania\" class=\"col-sm-2 control-label\">Compania</label>\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t<select id=\"listado_de_companias\" name=\"compania\"\n");
      out.write("\t\t\t\t\tclass=\"form-control\">\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<label for=\"estado_licencia\" class=\"col-sm-2 control-label\">Caducidad\n");
      out.write("\t\t\t\tLicencia</label>\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t<input name=\"caducidad_licencia\" type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\tid=\"caducidad_licencia\"\n");
      out.write("\t\t\t\t\tplaceholder=\"Caducidad Licencia: ej(02/03/2015 08:45)\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<div class=\"col-sm-offset-2 col-sm-10\">\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"pasajero\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pasajero.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-default\">Insertar\n");
      out.write("\t\t\t\t\tAvión</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("\t<!-- Librería jQuery requerida por los plugins de JavaScript -->\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery.js\"></script>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-1.8.3.min.js\"\n");
      out.write("\t\tcharset=\"UTF-8\"></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap-datetimepicker.js\"\n");
      out.write("\t\tcharset=\"UTF-8\"></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/locales/bootstrap-datetimepicker.fr.js\"\n");
      out.write("\t\tcharset=\"UTF-8\"></script>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t$('.form_datetime').datetimepicker({\n");
      out.write("\t\t\t//language:  'fr',\n");
      out.write("\t\t\tweekStart : 1,\n");
      out.write("\t\t\ttodayBtn : 1,\n");
      out.write("\t\t\tautoclose : 1,\n");
      out.write("\t\t\ttodayHighlight : 1,\n");
      out.write("\t\t\tstartView : 2,\n");
      out.write("\t\t\tforceParse : 0,\n");
      out.write("\t\t\tshowMeridian : 1\n");
      out.write("\t\t});\n");
      out.write("\t\t$('.form_date').datetimepicker({\n");
      out.write("\t\t\tlanguage : 'fr',\n");
      out.write("\t\t\tweekStart : 1,\n");
      out.write("\t\t\ttodayBtn : 1,\n");
      out.write("\t\t\tautoclose : 1,\n");
      out.write("\t\t\ttodayHighlight : 1,\n");
      out.write("\t\t\tstartView : 2,\n");
      out.write("\t\t\tminView : 2,\n");
      out.write("\t\t\tforceParse : 0\n");
      out.write("\t\t});\n");
      out.write("\t\t$('.form_time').datetimepicker({\n");
      out.write("\t\t\tlanguage : 'fr',\n");
      out.write("\t\t\tweekStart : 1,\n");
      out.write("\t\t\ttodayBtn : 1,\n");
      out.write("\t\t\tautoclose : 1,\n");
      out.write("\t\t\ttodayHighlight : 1,\n");
      out.write("\t\t\tstartView : 1,\n");
      out.write("\t\t\tminView : 0,\n");
      out.write("\t\t\tmaxView : 1,\n");
      out.write("\t\t\tforceParse : 0\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/avion/formAvion.jsp(83,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("companias");
    // /WEB-INF/views/avion/formAvion.jsp(83,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/avion/formAvion.jsp(83,4) '${sessionScope['listaCompanias']}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${sessionScope['listaCompanias']}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/avion/formAvion.jsp(86,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("comp");
    // /WEB-INF/views/avion/formAvion.jsp(86,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/avion/formAvion.jsp(86,5) '${companias}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${companias}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
