package com.innova4b.model;
// Generated 12-abr-2015 18:31:08 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ruta generated by hbm2java
 */
@Entity
@Table(name="ruta"
    ,catalog="aena"
)
public class Ruta  implements java.io.Serializable {


     private RutaId id;
     private Aeropuerto aeropuertoByAeropuertoIdAeropuerto;
     private Aeropuerto aeropuertoByAeropuertoIdAeropuerto1;
     private Set<Compania> companias = new HashSet<Compania>(0);
     private Set<Avion> avions = new HashSet<Avion>(0);

    public Ruta() {
    }

	
    public Ruta(RutaId id, Aeropuerto aeropuertoByAeropuertoIdAeropuerto, Aeropuerto aeropuertoByAeropuertoIdAeropuerto1) {
        this.id = id;
        this.aeropuertoByAeropuertoIdAeropuerto = aeropuertoByAeropuertoIdAeropuerto;
        this.aeropuertoByAeropuertoIdAeropuerto1 = aeropuertoByAeropuertoIdAeropuerto1;
    }
    public Ruta(RutaId id, Aeropuerto aeropuertoByAeropuertoIdAeropuerto, Aeropuerto aeropuertoByAeropuertoIdAeropuerto1, Set<Compania> companias, Set<Avion> avions) {
       this.id = id;
       this.aeropuertoByAeropuertoIdAeropuerto = aeropuertoByAeropuertoIdAeropuerto;
       this.aeropuertoByAeropuertoIdAeropuerto1 = aeropuertoByAeropuertoIdAeropuerto1;
       this.companias = companias;
       this.avions = avions;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idRuta", column=@Column(name="idRuta", nullable=false) ), 
        @AttributeOverride(name="aeropuertoIdAeropuerto", column=@Column(name="aeropuerto_idAeropuerto", nullable=false) ), 
        @AttributeOverride(name="aeropuertoIdAeropuerto1", column=@Column(name="aeropuerto_idAeropuerto1", nullable=false) ) } )
    public RutaId getId() {
        return this.id;
    }
    
    public void setId(RutaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aeropuerto_idAeropuerto", nullable=false, insertable=false, updatable=false)
    public Aeropuerto getAeropuertoByAeropuertoIdAeropuerto() {
        return this.aeropuertoByAeropuertoIdAeropuerto;
    }
    
    public void setAeropuertoByAeropuertoIdAeropuerto(Aeropuerto aeropuertoByAeropuertoIdAeropuerto) {
        this.aeropuertoByAeropuertoIdAeropuerto = aeropuertoByAeropuertoIdAeropuerto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aeropuerto_idAeropuerto1", nullable=false, insertable=false, updatable=false)
    public Aeropuerto getAeropuertoByAeropuertoIdAeropuerto1() {
        return this.aeropuertoByAeropuertoIdAeropuerto1;
    }
    
    public void setAeropuertoByAeropuertoIdAeropuerto1(Aeropuerto aeropuertoByAeropuertoIdAeropuerto1) {
        this.aeropuertoByAeropuertoIdAeropuerto1 = aeropuertoByAeropuertoIdAeropuerto1;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="compania_has_ruta", catalog="aena", joinColumns = { 
        @JoinColumn(name="ruta_idRuta", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="compania_idCompania", nullable=false, updatable=false) })
    public Set<Compania> getCompanias() {
        return this.companias;
    }
    
    public void setCompanias(Set<Compania> companias) {
        this.companias = companias;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="ruta_has_avion", catalog="aena", joinColumns = { 
        @JoinColumn(name="ruta_idRuta", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="avion_idAvion", nullable=false, updatable=false) })
    public Set<Avion> getAvions() {
        return this.avions;
    }
    
    public void setAvions(Set<Avion> avions) {
        this.avions = avions;
    }




}


