package com.innova4b.model;
// Generated 12-abr-2015 23:05:10 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Billete generated by hbm2java
 */
@Entity
@Table(name="billete"
    ,catalog="aena"
)
public class Billete  implements java.io.Serializable {


     private int idBillete;
     private Avion avion;
     private Pasajero pasajero;
     private String codgo;
     private String asiento;
     private Date fecha;
     private String estado;

    public Billete() {
    }

	
    public Billete(int idBillete, Avion avion, Pasajero pasajero, String codgo, String estado) {
        this.idBillete = idBillete;
        this.avion = avion;
        this.pasajero = pasajero;
        this.codgo = codgo;
        this.estado = estado;
    }
    public Billete(int idBillete, Avion avion, Pasajero pasajero, String codgo, String asiento, Date fecha, String estado) {
       this.idBillete = idBillete;
       this.avion = avion;
       this.pasajero = pasajero;
       this.codgo = codgo;
       this.asiento = asiento;
       this.fecha = fecha;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="idBillete", unique=true, nullable=false)
    public int getIdBillete() {
        return this.idBillete;
    }
    
    public void setIdBillete(int idBillete) {
        this.idBillete = idBillete;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="avion_idAvion", nullable=false)
    public Avion getAvion() {
        return this.avion;
    }
    
    public void setAvion(Avion avion) {
        this.avion = avion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pasajero_idPasajero", nullable=false)
    public Pasajero getPasajero() {
        return this.pasajero;
    }
    
    public void setPasajero(Pasajero pasajero) {
        this.pasajero = pasajero;
    }

    
    @Column(name="codgo", nullable=false, length=45)
    public String getCodgo() {
        return this.codgo;
    }
    
    public void setCodgo(String codgo) {
        this.codgo = codgo;
    }

    
    @Column(name="asiento", length=10)
    public String getAsiento() {
        return this.asiento;
    }
    
    public void setAsiento(String asiento) {
        this.asiento = asiento;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="estado", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


