package com.innova4b.model;
// Generated 12-abr-2015 23:05:10 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Compania generated by hbm2java
 */
@Entity
@Table(name="compania"
    ,catalog="aena"
)
public class Compania  implements java.io.Serializable {


     private int idCompania;
     private String nombre;
     private Set<Avion> avions = new HashSet<Avion>(0);
     private Set<Ruta> rutas = new HashSet<Ruta>(0);

    public Compania() {
    }

	
    public Compania(int idCompania) {
        this.idCompania = idCompania;
    }
    public Compania(int idCompania, String nombre, Set<Avion> avions, Set<Ruta> rutas) {
       this.idCompania = idCompania;
       this.nombre = nombre;
       this.avions = avions;
       this.rutas = rutas;
    }
   
     @Id 

    
    @Column(name="idCompania", unique=true, nullable=false)
    public int getIdCompania() {
        return this.idCompania;
    }
    
    public void setIdCompania(int idCompania) {
        this.idCompania = idCompania;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="compania")
    public Set<Avion> getAvions() {
        return this.avions;
    }
    
    public void setAvions(Set<Avion> avions) {
        this.avions = avions;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="compania_has_ruta", catalog="aena", joinColumns = { 
        @JoinColumn(name="compania_idCompania", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="ruta_idRuta", nullable=false, updatable=false) })
    public Set<Ruta> getRutas() {
        return this.rutas;
    }
    
    public void setRutas(Set<Ruta> rutas) {
        this.rutas = rutas;
    }




}


