package com.innova4b.model;
// Generated 12-abr-2015 23:05:10 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmbarqueId generated by hbm2java
 */
@Embeddable
public class EmbarqueId  implements java.io.Serializable {


     private int idEmbarque;
     private int aeropuertoIdAeropuerto;

    public EmbarqueId() {
    }

    public EmbarqueId(int idEmbarque, int aeropuertoIdAeropuerto) {
       this.idEmbarque = idEmbarque;
       this.aeropuertoIdAeropuerto = aeropuertoIdAeropuerto;
    }
   


    @Column(name="idEmbarque", nullable=false)
    public int getIdEmbarque() {
        return this.idEmbarque;
    }
    
    public void setIdEmbarque(int idEmbarque) {
        this.idEmbarque = idEmbarque;
    }


    @Column(name="aeropuerto_idAeropuerto", nullable=false)
    public int getAeropuertoIdAeropuerto() {
        return this.aeropuertoIdAeropuerto;
    }
    
    public void setAeropuertoIdAeropuerto(int aeropuertoIdAeropuerto) {
        this.aeropuertoIdAeropuerto = aeropuertoIdAeropuerto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmbarqueId) ) return false;
		 EmbarqueId castOther = ( EmbarqueId ) other; 
         
		 return (this.getIdEmbarque()==castOther.getIdEmbarque())
 && (this.getAeropuertoIdAeropuerto()==castOther.getAeropuertoIdAeropuerto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEmbarque();
         result = 37 * result + this.getAeropuertoIdAeropuerto();
         return result;
   }   


}


