package com.innova4b.model;
// Generated 12-abr-2015 23:05:10 by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Embarque generated by hbm2java
 */
@Entity
@Table(name="embarque"
    ,catalog="aena"
)
public class Embarque  implements java.io.Serializable {


     private EmbarqueId id;
     private Aeropuerto aeropuerto;
     private int num;

    public Embarque() {
    }

    public Embarque(EmbarqueId id, Aeropuerto aeropuerto, int num) {
       this.id = id;
       this.aeropuerto = aeropuerto;
       this.num = num;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEmbarque", column=@Column(name="idEmbarque", nullable=false) ), 
        @AttributeOverride(name="aeropuertoIdAeropuerto", column=@Column(name="aeropuerto_idAeropuerto", nullable=false) ) } )
    public EmbarqueId getId() {
        return this.id;
    }
    
    public void setId(EmbarqueId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aeropuerto_idAeropuerto", nullable=false, insertable=false, updatable=false)
    public Aeropuerto getAeropuerto() {
        return this.aeropuerto;
    }
    
    public void setAeropuerto(Aeropuerto aeropuerto) {
        this.aeropuerto = aeropuerto;
    }

    
    @Column(name="num", nullable=false)
    public int getNum() {
        return this.num;
    }
    
    public void setNum(int num) {
        this.num = num;
    }




}


