package com.innova4b.model;
// Generated 12-abr-2015 23:05:10 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name="estado"
    ,catalog="aena"
)
public class Estado  implements java.io.Serializable {


     private int idestado;
     private String nombre;
     private Set<Avion> avions = new HashSet<Avion>(0);

    public Estado() {
    }

	
    public Estado(int idestado) {
        this.idestado = idestado;
    }
    public Estado(int idestado, String nombre, Set<Avion> avions) {
       this.idestado = idestado;
       this.nombre = nombre;
       this.avions = avions;
    }
   
     @Id 

    
    @Column(name="idestado", unique=true, nullable=false)
    public int getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(int idestado) {
        this.idestado = idestado;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estado")
    public Set<Avion> getAvions() {
        return this.avions;
    }
    
    public void setAvions(Set<Avion> avions) {
        this.avions = avions;
    }




}


