package com.innova4b.model;
// Generated 12-abr-2015 23:05:10 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pasajero generated by hbm2java
 */
@Entity
@Table(name="pasajero"
    ,catalog="aena"
)
public class Pasajero  implements java.io.Serializable {


     private int idPasajero;
     private String nombre;
     private String apellidos;
     private Date fechaNacimiento;
     private Set<Billete> billetes = new HashSet<Billete>(0);

    public Pasajero() {
    }

	
    public Pasajero(int idPasajero) {
        this.idPasajero = idPasajero;
    }
    public Pasajero(int idPasajero, String nombre, String apellidos, Date fechaNacimiento, Set<Billete> billetes) {
       this.idPasajero = idPasajero;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.fechaNacimiento = fechaNacimiento;
       this.billetes = billetes;
    }
   
     @Id 

    
    @Column(name="idPasajero", unique=true, nullable=false)
    public int getIdPasajero() {
        return this.idPasajero;
    }
    
    public void setIdPasajero(int idPasajero) {
        this.idPasajero = idPasajero;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellidos", length=45)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_nacimiento", length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pasajero")
    public Set<Billete> getBilletes() {
        return this.billetes;
    }
    
    public void setBilletes(Set<Billete> billetes) {
        this.billetes = billetes;
    }




}


