// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innova4b.model;

import com.innova4b.model.Aeropuerto;
import com.innova4b.model.AeropuertoDataOnDemand;
import com.innova4b.model.AeropuertoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AeropuertoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AeropuertoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AeropuertoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AeropuertoIntegrationTest: @Transactional;
    
    @Autowired
    AeropuertoDataOnDemand AeropuertoIntegrationTest.dod;
    
    @Test
    public void AeropuertoIntegrationTest.testCountAeropuertoes() {
        Assert.assertNotNull("Data on demand for 'Aeropuerto' failed to initialize correctly", dod.getRandomAeropuerto());
        long count = Aeropuerto.countAeropuertoes();
        Assert.assertTrue("Counter for 'Aeropuerto' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AeropuertoIntegrationTest.testFindAeropuerto() {
        Aeropuerto obj = dod.getRandomAeropuerto();
        Assert.assertNotNull("Data on demand for 'Aeropuerto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Aeropuerto' failed to provide an identifier", id);
        obj = Aeropuerto.findAeropuerto(id);
        Assert.assertNotNull("Find method for 'Aeropuerto' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Aeropuerto' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AeropuertoIntegrationTest.testFindAllAeropuertoes() {
        Assert.assertNotNull("Data on demand for 'Aeropuerto' failed to initialize correctly", dod.getRandomAeropuerto());
        long count = Aeropuerto.countAeropuertoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Aeropuerto', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Aeropuerto> result = Aeropuerto.findAllAeropuertoes();
        Assert.assertNotNull("Find all method for 'Aeropuerto' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Aeropuerto' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AeropuertoIntegrationTest.testFindAeropuertoEntries() {
        Assert.assertNotNull("Data on demand for 'Aeropuerto' failed to initialize correctly", dod.getRandomAeropuerto());
        long count = Aeropuerto.countAeropuertoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Aeropuerto> result = Aeropuerto.findAeropuertoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Aeropuerto' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Aeropuerto' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AeropuertoIntegrationTest.testFlush() {
        Aeropuerto obj = dod.getRandomAeropuerto();
        Assert.assertNotNull("Data on demand for 'Aeropuerto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Aeropuerto' failed to provide an identifier", id);
        obj = Aeropuerto.findAeropuerto(id);
        Assert.assertNotNull("Find method for 'Aeropuerto' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAeropuerto(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Aeropuerto' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AeropuertoIntegrationTest.testMergeUpdate() {
        Aeropuerto obj = dod.getRandomAeropuerto();
        Assert.assertNotNull("Data on demand for 'Aeropuerto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Aeropuerto' failed to provide an identifier", id);
        obj = Aeropuerto.findAeropuerto(id);
        boolean modified =  dod.modifyAeropuerto(obj);
        Integer currentVersion = obj.getVersion();
        Aeropuerto merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Aeropuerto' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AeropuertoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Aeropuerto' failed to initialize correctly", dod.getRandomAeropuerto());
        Aeropuerto obj = dod.getNewTransientAeropuerto(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Aeropuerto' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Aeropuerto' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Aeropuerto' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AeropuertoIntegrationTest.testRemove() {
        Aeropuerto obj = dod.getRandomAeropuerto();
        Assert.assertNotNull("Data on demand for 'Aeropuerto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Aeropuerto' failed to provide an identifier", id);
        obj = Aeropuerto.findAeropuerto(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Aeropuerto' with identifier '" + id + "'", Aeropuerto.findAeropuerto(id));
    }
    
}
