// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innova4b.model;

import com.innova4b.model.Aeropuerto;
import com.innova4b.model.AeropuertoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AeropuertoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AeropuertoDataOnDemand: @Component;
    
    private Random AeropuertoDataOnDemand.rnd = new SecureRandom();
    
    private List<Aeropuerto> AeropuertoDataOnDemand.data;
    
    public Aeropuerto AeropuertoDataOnDemand.getNewTransientAeropuerto(int index) {
        Aeropuerto obj = new Aeropuerto();
        setIdAeropuerto(obj, index);
        setNombre(obj, index);
        setNumPuertas(obj, index);
        setPais(obj, index);
        return obj;
    }
    
    public void AeropuertoDataOnDemand.setIdAeropuerto(Aeropuerto obj, int index) {
        Long idAeropuerto = new Integer(index).longValue();
        obj.setIdAeropuerto(idAeropuerto);
    }
    
    public void AeropuertoDataOnDemand.setNombre(Aeropuerto obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public void AeropuertoDataOnDemand.setNumPuertas(Aeropuerto obj, int index) {
        int numPuertas = index;
        obj.setNumPuertas(numPuertas);
    }
    
    public void AeropuertoDataOnDemand.setPais(Aeropuerto obj, int index) {
        String pais = "pais_" + index;
        obj.setPais(pais);
    }
    
    public Aeropuerto AeropuertoDataOnDemand.getSpecificAeropuerto(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Aeropuerto obj = data.get(index);
        Long id = obj.getId();
        return Aeropuerto.findAeropuerto(id);
    }
    
    public Aeropuerto AeropuertoDataOnDemand.getRandomAeropuerto() {
        init();
        Aeropuerto obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Aeropuerto.findAeropuerto(id);
    }
    
    public boolean AeropuertoDataOnDemand.modifyAeropuerto(Aeropuerto obj) {
        return false;
    }
    
    public void AeropuertoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Aeropuerto.findAeropuertoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Aeropuerto' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Aeropuerto>();
        for (int i = 0; i < 10; i++) {
            Aeropuerto obj = getNewTransientAeropuerto(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
