// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innova4b.model;

import com.innova4b.model.Avion;
import com.innova4b.model.AvionDataOnDemand;
import com.innova4b.model.AvionIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AvionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AvionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AvionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AvionIntegrationTest: @Transactional;
    
    @Autowired
    AvionDataOnDemand AvionIntegrationTest.dod;
    
    @Test
    public void AvionIntegrationTest.testCountAvions() {
        Assert.assertNotNull("Data on demand for 'Avion' failed to initialize correctly", dod.getRandomAvion());
        long count = Avion.countAvions();
        Assert.assertTrue("Counter for 'Avion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AvionIntegrationTest.testFindAvion() {
        Avion obj = dod.getRandomAvion();
        Assert.assertNotNull("Data on demand for 'Avion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Avion' failed to provide an identifier", id);
        obj = Avion.findAvion(id);
        Assert.assertNotNull("Find method for 'Avion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Avion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AvionIntegrationTest.testFindAllAvions() {
        Assert.assertNotNull("Data on demand for 'Avion' failed to initialize correctly", dod.getRandomAvion());
        long count = Avion.countAvions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Avion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Avion> result = Avion.findAllAvions();
        Assert.assertNotNull("Find all method for 'Avion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Avion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AvionIntegrationTest.testFindAvionEntries() {
        Assert.assertNotNull("Data on demand for 'Avion' failed to initialize correctly", dod.getRandomAvion());
        long count = Avion.countAvions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Avion> result = Avion.findAvionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Avion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Avion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AvionIntegrationTest.testFlush() {
        Avion obj = dod.getRandomAvion();
        Assert.assertNotNull("Data on demand for 'Avion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Avion' failed to provide an identifier", id);
        obj = Avion.findAvion(id);
        Assert.assertNotNull("Find method for 'Avion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAvion(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Avion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AvionIntegrationTest.testMergeUpdate() {
        Avion obj = dod.getRandomAvion();
        Assert.assertNotNull("Data on demand for 'Avion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Avion' failed to provide an identifier", id);
        obj = Avion.findAvion(id);
        boolean modified =  dod.modifyAvion(obj);
        Integer currentVersion = obj.getVersion();
        Avion merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Avion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AvionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Avion' failed to initialize correctly", dod.getRandomAvion());
        Avion obj = dod.getNewTransientAvion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Avion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Avion' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Avion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AvionIntegrationTest.testRemove() {
        Avion obj = dod.getRandomAvion();
        Assert.assertNotNull("Data on demand for 'Avion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Avion' failed to provide an identifier", id);
        obj = Avion.findAvion(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Avion' with identifier '" + id + "'", Avion.findAvion(id));
    }
    
}
