// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innova4b.model;

import com.innova4b.model.Billete;
import com.innova4b.model.BilleteDataOnDemand;
import com.innova4b.model.BilleteIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BilleteIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BilleteIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BilleteIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BilleteIntegrationTest: @Transactional;
    
    @Autowired
    BilleteDataOnDemand BilleteIntegrationTest.dod;
    
    @Test
    public void BilleteIntegrationTest.testCountBilletes() {
        Assert.assertNotNull("Data on demand for 'Billete' failed to initialize correctly", dod.getRandomBillete());
        long count = Billete.countBilletes();
        Assert.assertTrue("Counter for 'Billete' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BilleteIntegrationTest.testFindBillete() {
        Billete obj = dod.getRandomBillete();
        Assert.assertNotNull("Data on demand for 'Billete' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Billete' failed to provide an identifier", id);
        obj = Billete.findBillete(id);
        Assert.assertNotNull("Find method for 'Billete' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Billete' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BilleteIntegrationTest.testFindAllBilletes() {
        Assert.assertNotNull("Data on demand for 'Billete' failed to initialize correctly", dod.getRandomBillete());
        long count = Billete.countBilletes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Billete', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Billete> result = Billete.findAllBilletes();
        Assert.assertNotNull("Find all method for 'Billete' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Billete' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BilleteIntegrationTest.testFindBilleteEntries() {
        Assert.assertNotNull("Data on demand for 'Billete' failed to initialize correctly", dod.getRandomBillete());
        long count = Billete.countBilletes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Billete> result = Billete.findBilleteEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Billete' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Billete' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BilleteIntegrationTest.testFlush() {
        Billete obj = dod.getRandomBillete();
        Assert.assertNotNull("Data on demand for 'Billete' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Billete' failed to provide an identifier", id);
        obj = Billete.findBillete(id);
        Assert.assertNotNull("Find method for 'Billete' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBillete(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Billete' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BilleteIntegrationTest.testMergeUpdate() {
        Billete obj = dod.getRandomBillete();
        Assert.assertNotNull("Data on demand for 'Billete' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Billete' failed to provide an identifier", id);
        obj = Billete.findBillete(id);
        boolean modified =  dod.modifyBillete(obj);
        Integer currentVersion = obj.getVersion();
        Billete merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Billete' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BilleteIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Billete' failed to initialize correctly", dod.getRandomBillete());
        Billete obj = dod.getNewTransientBillete(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Billete' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Billete' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Billete' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BilleteIntegrationTest.testRemove() {
        Billete obj = dod.getRandomBillete();
        Assert.assertNotNull("Data on demand for 'Billete' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Billete' failed to provide an identifier", id);
        obj = Billete.findBillete(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Billete' with identifier '" + id + "'", Billete.findBillete(id));
    }
    
}
