// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innova4b.model;

import com.innova4b.model.Pasajero;
import com.innova4b.model.PasajeroDataOnDemand;
import com.innova4b.model.PasajeroIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PasajeroIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PasajeroIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PasajeroIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PasajeroIntegrationTest: @Transactional;
    
    @Autowired
    PasajeroDataOnDemand PasajeroIntegrationTest.dod;
    
    @Test
    public void PasajeroIntegrationTest.testCountPasajeroes() {
        Assert.assertNotNull("Data on demand for 'Pasajero' failed to initialize correctly", dod.getRandomPasajero());
        long count = Pasajero.countPasajeroes();
        Assert.assertTrue("Counter for 'Pasajero' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PasajeroIntegrationTest.testFindPasajero() {
        Pasajero obj = dod.getRandomPasajero();
        Assert.assertNotNull("Data on demand for 'Pasajero' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pasajero' failed to provide an identifier", id);
        obj = Pasajero.findPasajero(id);
        Assert.assertNotNull("Find method for 'Pasajero' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Pasajero' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PasajeroIntegrationTest.testFindAllPasajeroes() {
        Assert.assertNotNull("Data on demand for 'Pasajero' failed to initialize correctly", dod.getRandomPasajero());
        long count = Pasajero.countPasajeroes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Pasajero', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Pasajero> result = Pasajero.findAllPasajeroes();
        Assert.assertNotNull("Find all method for 'Pasajero' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Pasajero' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PasajeroIntegrationTest.testFindPasajeroEntries() {
        Assert.assertNotNull("Data on demand for 'Pasajero' failed to initialize correctly", dod.getRandomPasajero());
        long count = Pasajero.countPasajeroes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Pasajero> result = Pasajero.findPasajeroEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Pasajero' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Pasajero' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PasajeroIntegrationTest.testFlush() {
        Pasajero obj = dod.getRandomPasajero();
        Assert.assertNotNull("Data on demand for 'Pasajero' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pasajero' failed to provide an identifier", id);
        obj = Pasajero.findPasajero(id);
        Assert.assertNotNull("Find method for 'Pasajero' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPasajero(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Pasajero' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PasajeroIntegrationTest.testMergeUpdate() {
        Pasajero obj = dod.getRandomPasajero();
        Assert.assertNotNull("Data on demand for 'Pasajero' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pasajero' failed to provide an identifier", id);
        obj = Pasajero.findPasajero(id);
        boolean modified =  dod.modifyPasajero(obj);
        Integer currentVersion = obj.getVersion();
        Pasajero merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Pasajero' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PasajeroIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Pasajero' failed to initialize correctly", dod.getRandomPasajero());
        Pasajero obj = dod.getNewTransientPasajero(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Pasajero' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Pasajero' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Pasajero' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PasajeroIntegrationTest.testRemove() {
        Pasajero obj = dod.getRandomPasajero();
        Assert.assertNotNull("Data on demand for 'Pasajero' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pasajero' failed to provide an identifier", id);
        obj = Pasajero.findPasajero(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Pasajero' with identifier '" + id + "'", Pasajero.findPasajero(id));
    }
    
}
