package com.innova4b;

// Generated 11-abr-2015 17:53:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Aeropuerto generated by hbm2java
 */
@Entity
@Table(name = "aeropuerto", catalog = "aenabbdd", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Aeropuerto implements java.io.Serializable {

	private int idAeropuerto;
	private String nombre;
	private Integer numPuertas;
	private String pais;
	private Set<Ruta> rutasForAeropuertoIdAeropuerto1 = new HashSet<Ruta>(0);
	private Set<Ruta> rutasForAeropuertoIdAeropuerto = new HashSet<Ruta>(0);

	public Aeropuerto() {
	}

	public Aeropuerto(int idAeropuerto) {
		this.idAeropuerto = idAeropuerto;
	}

	public Aeropuerto(int idAeropuerto, String nombre, Integer numPuertas,
			String pais, Set<Ruta> rutasForAeropuertoIdAeropuerto1,
			Set<Ruta> rutasForAeropuertoIdAeropuerto) {
		this.idAeropuerto = idAeropuerto;
		this.nombre = nombre;
		this.numPuertas = numPuertas;
		this.pais = pais;
		this.rutasForAeropuertoIdAeropuerto1 = rutasForAeropuertoIdAeropuerto1;
		this.rutasForAeropuertoIdAeropuerto = rutasForAeropuertoIdAeropuerto;
	}

	@Id
	@Column(name = "idAeropuerto", unique = true, nullable = false)
	public int getIdAeropuerto() {
		return this.idAeropuerto;
	}

	public void setIdAeropuerto(int idAeropuerto) {
		this.idAeropuerto = idAeropuerto;
	}

	@Column(name = "nombre", unique = true, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "num_puertas")
	public Integer getNumPuertas() {
		return this.numPuertas;
	}

	public void setNumPuertas(Integer numPuertas) {
		this.numPuertas = numPuertas;
	}

	@Column(name = "pais", length = 45)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aeropuertoByAeropuertoIdAeropuerto1")
	public Set<Ruta> getRutasForAeropuertoIdAeropuerto1() {
		return this.rutasForAeropuertoIdAeropuerto1;
	}

	public void setRutasForAeropuertoIdAeropuerto1(
			Set<Ruta> rutasForAeropuertoIdAeropuerto1) {
		this.rutasForAeropuertoIdAeropuerto1 = rutasForAeropuertoIdAeropuerto1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aeropuertoByAeropuertoIdAeropuerto")
	public Set<Ruta> getRutasForAeropuertoIdAeropuerto() {
		return this.rutasForAeropuertoIdAeropuerto;
	}

	public void setRutasForAeropuertoIdAeropuerto(
			Set<Ruta> rutasForAeropuertoIdAeropuerto) {
		this.rutasForAeropuertoIdAeropuerto = rutasForAeropuertoIdAeropuerto;
	}

}
