package com.innova4b;

// Generated 11-abr-2015 17:53:23 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RutaId generated by hbm2java
 */
@Embeddable
public class RutaId implements java.io.Serializable {

	private int idRuta;
	private int aeropuertoIdAeropuerto;
	private int aeropuertoIdAeropuerto1;

	public RutaId() {
	}

	public RutaId(int idRuta, int aeropuertoIdAeropuerto,
			int aeropuertoIdAeropuerto1) {
		this.idRuta = idRuta;
		this.aeropuertoIdAeropuerto = aeropuertoIdAeropuerto;
		this.aeropuertoIdAeropuerto1 = aeropuertoIdAeropuerto1;
	}

	@Column(name = "idRuta", nullable = false)
	public int getIdRuta() {
		return this.idRuta;
	}

	public void setIdRuta(int idRuta) {
		this.idRuta = idRuta;
	}

	@Column(name = "aeropuerto_idAeropuerto", nullable = false)
	public int getAeropuertoIdAeropuerto() {
		return this.aeropuertoIdAeropuerto;
	}

	public void setAeropuertoIdAeropuerto(int aeropuertoIdAeropuerto) {
		this.aeropuertoIdAeropuerto = aeropuertoIdAeropuerto;
	}

	@Column(name = "aeropuerto_idAeropuerto1", nullable = false)
	public int getAeropuertoIdAeropuerto1() {
		return this.aeropuertoIdAeropuerto1;
	}

	public void setAeropuertoIdAeropuerto1(int aeropuertoIdAeropuerto1) {
		this.aeropuertoIdAeropuerto1 = aeropuertoIdAeropuerto1;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RutaId))
			return false;
		RutaId castOther = (RutaId) other;

		return (this.getIdRuta() == castOther.getIdRuta())
				&& (this.getAeropuertoIdAeropuerto() == castOther
						.getAeropuertoIdAeropuerto())
				&& (this.getAeropuertoIdAeropuerto1() == castOther
						.getAeropuertoIdAeropuerto1());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRuta();
		result = 37 * result + this.getAeropuertoIdAeropuerto();
		result = 37 * result + this.getAeropuertoIdAeropuerto1();
		return result;
	}

}
